apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
  kubectl: 
    manifests: 
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: gauravkhede/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: gauravkhede/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '**/*.ts'
            dest: .
    - image: gauravkhede/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: gauravkhede/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: gauravkhede/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .